# Generated by Django 4.0.6 on 2022-08-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
