# Generated by Django 4.0.6 on 2022-08-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
    ]
