# Generated by Django 4.0.6 on 2022-08-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_admin_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
