# Generated by Django 4.0.6 on 2022-08-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
