# Generated by Django 4.0.6 on 2022-08-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User App',
        ),
    ]
