# Generated by Django 4.0.6 on 2022-08-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Userr',
        ),
    ]
