# Generated by Django 4.0.6 on 2022-08-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Pengguna',
        ),
    ]
