# Generated by Django 4.0.6 on 2022-08-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='buku',
        ),
    ]
