# Generated by Django 4.0.6 on 2022-08-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
