# Generated by Django 4.0.6 on 2022-08-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User App'},
        ),
    ]
