# Generated by Django 4.0.6 on 2022-08-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
