# Generated by Django 4.0.6 on 2022-08-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0023_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AuthUser',
        ),
    ]
