# Generated by Django 4.0.6 on 2022-08-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_admin_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
